services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      # Use o endpoint público ou privado do seu banco no RDS
      - DB_HOST=tooglemaster-app-db.c5m42qk2wlfc.us-east-1.rds.amazonaws.com
      - DB_NAME=togglemaster
      - DB_USER=postgres
      - DB_PASSWORD=rootroot
      - DB_PORT=5432

